filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/m1-consumer-service-all.log
    fields:
      app: m1-consumer
      env: dev
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/m2-provider-service-all.log
    fields:
      app: m2-provider
      env: dev
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/my-gateway-service-all.log
    fields:
      app: my-gateway
      env: dev
    fields_under_root: true

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
  - drop_fields:
      fields: ["host", "agent", "ecs", "input", "log", "@version"]
      ignore_missing: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "m1-consumer-%{+yyyy.MM.dd}"
      when.equals:
        app: "m1-consumer"
    - index: "m2-provider-%{+yyyy.MM.dd}"
      when.equals:
        app: "m2-provider"
    - index: "my-gateway-%{+yyyy.MM.dd}"
      when.equals:
        app: "my-gateway"

setup.template.name: "cloud-demo"
setup.template.pattern: "cloud-demo-*"
